// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID    int64
	Email     string
	Password  string
	Role      int64
	UserUuid  pgtype.UUID
	CreatedAt pgtype.Timestamp
}
